import '@/public/styles/globals.css';
import React, { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ThemeProviderWrapper from '@/components/Wrappers/ThemeProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="pt-BR">
			<body className={inter.className}>
				<ThemeProviderWrapper>
					{children}
				</ThemeProviderWrapper>
			</body>
		</html>
	);
};