import GlobalStyles from "@/public/styles/global";
import React, { ReactNode } from 'react';
import StyledComponentsRegistry from "@/lib/registry";
import ThemeProviderWrapper from '@/components/Wrappers/ThemeProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: './favicon.ico',
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="pt-BR">
			<body className={inter.className}>
				<GlobalStyles />
				<StyledComponentsRegistry>
					<ThemeProviderWrapper>
						{children}
					</ThemeProviderWrapper>
				</StyledComponentsRegistry>
			</body>
		</html>
	);
};